In [1]:
import numpy as np


In [2]:
data = [[1,2],[4,5]]

In [3]:
data = np.array(data)

In [4]:
data
x = data[:,0]
y = data[:,1]

In [5]:
x = x.reshape(2,1)
y = y.reshape(2,1)

In [6]:
x.shape

(2, 1)

In [7]:
y

array([[2],
       [5]])

In [8]:
w = np.array([[0]])
w.shape

(1, 1)

In [9]:
b = np.array([0])

In [10]:
y_ = np.matmul(x,w) + b

In [11]:
y_

array([[0],
       [0]])

In [12]:
np.square(y -y_)

array([[ 4],
       [25]], dtype=int32)

In [13]:
c = (1/2.0)*(np.sum(np.square(y - y_)))

In [14]:
c

14.5

In [15]:
dw = np.sum(np.sum(y - y_)*x)

In [16]:
dw

35

In [17]:
for i in range(200):
    dw = -np.sum(np.sum(y - y_) * x)
    db = -np.sum(y - y_)
    w = w - (0.1 * dw)
    b = b - (0.1 * db)
    y_ = np.matmul(x,w) + b


In [18]:
y_

array([[-1.91280105e+46],
       [-6.69480368e+46]])

In [19]:
w

array([[-1.59400088e+46]])

In [20]:
c = (1/2.0) * (np.sum(np.square(y-y_)))

In [21]:
c

2.423960209506634e+93